name: Build
on:
  push:
    branches:
    - dev

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu-latest: [20.04, 18.04]
        python-version: [3.6, 3.7]

    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    
    - name: Python checkout
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt
